### ISSUE TITLE
I got an error when I tested this plugin. @type (ArgumentError)

### ISSUE THREAD

**Issue by nobuyukioishi** [toyokazu/fluent-plugin-mqtt-io#1]
Thank you for this useful fluentd plugin.

I installed this one by
```
fluent-gem install fluent-plugin-mqtt-io
```

However, I get an error like below when I execute fluentd

``` Error Message
2017-07-19 02:01:49 +0900 [info]: reading config file path="/etc/fluent/fluent.conf"
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/config/section.rb:178:in `block in generate': format: init is specified, but there're parameters without default values:@type (ArgumentError)
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/config/section.rb:169:in `each'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/config/section.rb:169:in `generate'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/configurable.rb:94:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/plugin/base.rb:57:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/plugin_id.rb:39:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/log.rb:497:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/plugin/output.rb:239:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/plugin_helper/inject.rb:104:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/plugin_helper/formatter.rb:83:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluent-plugin-mqtt-io-0.3.1/lib/fluent/plugin/out_mqtt.rb:58:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/plugin.rb:164:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/agent.rb:130:in `add_match'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/agent.rb:72:in `block in configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/agent.rb:64:in `each'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/agent.rb:64:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/root_agent.rb:112:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/engine.rb:131:in `configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/engine.rb:96:in `run_configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/supervisor.rb:756:in `run_configure'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/supervisor.rb:538:in `dry_run'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/supervisor.rb:556:in `supervise'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/supervisor.rb:462:in `run_supervisor'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-0.14.19/bin/fluentd:5:in `<top (required)>'
	from /root/.rbenv/versions/2.4.1/bin/fluentd:22:in `load'
	from /root/.rbenv/versions/2.4.1/bin/fluentd:22:in `<main>'
```

Here is my fluentd.conf file.

```
<source>
  @type forward
</source>

<match sample.data>
  type mqtt
  host (broker's ip address)
  port (port)
</match>

<match fluent.**>
  @type file
  path /var/log/fluent/fluentd_internal.log
 </match>
 
 <match **>
   @type file
   path /var/log/fluent/else
   compress gz
 </match>
```

Is there anything wrong with my configuration?

Information:
Machine: RaspberryPi 3 with 2017-06-21-raspbian-jessie,
Fluentd version: 0.14.19

**Comment by toyokazu** [comment]
Hi,

Thank you for using the plugin.
I'm sorry that I've not fixed the README yet after migrating fluentd from 0.12 to 0.14. So, configuration examples are still for the version before 0.2.3.

Could you try `@type` instead of `type` in your configuration? The other configurations are also changed in fluentd 0.14 as described in the following slide:

https://www.slideshare.net/tagomoris/fluentd-v014-plugin-api-details

By the way, since the buffer function is not working correctly in this plugin, please use it without `<buffer>` options.

**Comment by nobuyukioishi** [comment]
Thank you for your quick reply.

I see. Would you tell me what does "0.2.3" mean?
I just tried with ruby 2.2.2, but it threw the same error.
(I also added @ before "type")

Also, I saw the slide, but I don't think I use any characteristics of fluentd 0.14  like <buffer>.

Do you have any idea?

```
/root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/config/section.rb:178:in `block in generate': format: init is specified, but there're parameters without default values:@type (ArgumentError)
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/config/section.rb:169:in `each'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/config/section.rb:169:in `generate'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/configurable.rb:94:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/plugin/base.rb:57:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/plugin_id.rb:39:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/log.rb:497:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/plugin/output.rb:239:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/plugin_helper/inject.rb:104:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/plugin_helper/formatter.rb:83:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluent-plugin-mqtt-io-0.3.1/lib/fluent/plugin/out_mqtt.rb:58:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/plugin.rb:164:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/agent.rb:130:in `add_match'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/agent.rb:72:in `block in configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/agent.rb:64:in `each'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/agent.rb:64:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/root_agent.rb:112:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/engine.rb:131:in `configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/engine.rb:96:in `run_configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/supervisor.rb:756:in `run_configure'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/supervisor.rb:538:in `dry_run'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/supervisor.rb:556:in `supervise'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/supervisor.rb:462:in `run_supervisor'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.14.19/bin/fluentd:5:in `<top (required)>'
	from /root/.rbenv/versions/2.2.2/bin/fluentd:23:in `load'
	from /root/.rbenv/versions/2.2.2/bin/fluentd:23:in `<main>
```

Thank you in advance.

**Comment by toyokazu** [comment]
Sorry for my insufficient explanation...
You seem to use fluent-plugin-mqtt-io version 0.3.1 from your log.
0.2.3 in the previous message means the version number of fluent-plugin-mqtt-io. Ruby version does not affect your problem.

From your log, missing `<format>` tag causes the error.
Would you try to add the following to your configuration? If you are using a different message format, please specify your preferable type (the following uses json).

```
<match sample.data>
  @type mqtt
  host (broker's ip address)
  port (port)
  <format>
    @type json
    add_newline false
  </format>
</match>
```

Best Regards

**Comment by nobuyukioishi** [comment]
Added <format> and it worked!

Since I am very new to fluentd, your quick and detailed responses really helped me.
 
Thank you very much.

**Comment by toyokazu** [comment]
Thank you for your feedback! Since this plugin is still under development, your feedback helps it very much :) Please feel free to ask here.

Best

**Comment by toyokazu** [comment]
`<buffer>` related bugs are fixed. So now you can use buffer function in 0.14 (but only sync buffered output).

Best
