### ISSUE TITLE
mqtt_out problem. Using Raspberry with 800c GSM Module

### ISSUE THREAD

**Issue by AbhishekChudekar** [toyokazu/fluent-plugin-mqtt-io#13]
2019-02-11 12:28:10 +0000 [error]: #0 The other error occurs in out_mqtt.,OpenSS                                                                                        L::SSL::SSLError,SSL_connect returned=1 errno=0 state=unknown state: unknown ale                                                                                        rt type
2019-02-11 12:28:10 +0000 [error]: #0 Retry in 2 sec
2019-02-11 12:28:15 +0000 [error]: #0 Timeout error occurs in out_mqtt.,Timeout:                                                                                        :Error,execution expired
2019-02-11 12:28:15 +0000 [error]: #0 Retry in 1 sec
2019-02-11 12:28:15 +0000 [warn]: #0 failed to flush the buffer. retry_time=5 ne                                                                                        xt_retry_seconds=2019-02-11 12:28:31 +0000 chunk="5819d6f3d299ba0524777cb175e652                                                                                        9b" error_class=OpenSSL::SSL::SSLError error="SSL_write: unknown alert type"
  2019-02-11 12:28:15 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/buffering.rb:                                                                                        322:in `syswrite'
  2019-02-11 12:28:15 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/buffering.rb:                                                                                        322:in `do_write'
  2019-02-11 12:28:15 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/buffering.rb:                                                                                        340:in `write'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/m                                                                                        qtt/client.rb:556:in `block in send_packet'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/m                                                                                        qtt/client.rb:555:in `synchronize'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/m                                                                                        qtt/client.rb:555:in `send_packet'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/m                                                                                        qtt/client.rb:328:in `disconnect'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mq                                                                                        tt-io-0.4.2/lib/fluent/plugin/mqtt_proxy.rb:93:in `retry_connect'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mq                                                                                        tt-io-0.4.2/lib/fluent/plugin/mqtt_proxy.rb:122:in `rescue in rescue_disconnecti                                                                                        on'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mq                                                                                        tt-io-0.4.2/lib/fluent/plugin/mqtt_proxy.rb:111:in `rescue_disconnection'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mq                                                                                        tt-io-0.4.2/lib/fluent/plugin/out_mqtt.rb:163:in `block in write'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/event.rb:323:in `each'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/event.rb:323:in `block in each'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/plugin/buffer/file_chunk.rb:172:in `open'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/event.rb:322:in `each'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mq                                                                                        tt-io-0.4.2/lib/fluent/plugin/out_mqtt.rb:162:in `write'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/plugin/output.rb:1123:in `try_flush'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/plugin/output.rb:1423:in `flush_thread_run'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/plugin/output.rb:452:in `block (2 levels) in start'
  2019-02-11 12:28:15 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-02-11 12:28:31 +0000 [error]: #0 The other error occurs in out_mqtt.,OpenSS                                                                                        L::SSL::SSLError,SSL_write: unknown alert type
2019-02-11 12:28:31 +0000 [error]: #0 Retry in 1 sec
2019-02-11 12:28:31 +0000 [warn]: #0 failed to flush the buffer. retry_time=6 ne                                                                                        xt_retry_seconds=2019-02-11 12:29:04 +0000 chunk="5819d6f3d299ba0524777cb175e652                                                                                        9b" error_class=OpenSSL::SSL::SSLError error="SSL_write: unknown alert type"
  2019-02-11 12:28:31 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/buffering.rb:                                                                                        322:in `syswrite'
  2019-02-11 12:28:31 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/buffering.rb:                                                                                        322:in `do_write'
  2019-02-11 12:28:31 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/buffering.rb:                                                                                        340:in `write'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/m                                                                                        qtt/client.rb:556:in `block in send_packet'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/m                                                                                        qtt/client.rb:555:in `synchronize'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/m                                                                                        qtt/client.rb:555:in `send_packet'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/m                                                                                        qtt/client.rb:328:in `disconnect'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mq                                                                                        tt-io-0.4.2/lib/fluent/plugin/mqtt_proxy.rb:93:in `retry_connect'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mq                                                                                        tt-io-0.4.2/lib/fluent/plugin/mqtt_proxy.rb:128:in `rescue in rescue_disconnecti                                                                                        on'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mq                                                                                        tt-io-0.4.2/lib/fluent/plugin/mqtt_proxy.rb:111:in `rescue_disconnection'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mq                                                                                        tt-io-0.4.2/lib/fluent/plugin/out_mqtt.rb:163:in `block in write'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/event.rb:323:in `each'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/event.rb:323:in `block in each'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/plugin/buffer/file_chunk.rb:172:in `open'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/event.rb:322:in `each'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mq                                                                                        tt-io-0.4.2/lib/fluent/plugin/out_mqtt.rb:162:in `write'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/plugin/output.rb:1123:in `try_flush'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/plugin/output.rb:1423:in `flush_thread_run'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/plugin/output.rb:452:in `block (2 levels) in start'
  2019-02-11 12:28:31 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.3/li                                                                                        b/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-02-11 12:29:04 +0000 [error]: #0 The other error occurs in out_mqtt.,OpenSS                                                                                        L::SSL::SSLError,SSL_write: unknown alert type
2019-02-11 12:29:04 +0000 [error]: #0 Retry in 1 sec
2019-02-11 12:29:04 +0000 [warn]: #0 failed to flush the buffer. retry_time=7 ne                                                                                        xt_retry_seconds=2019-02-11 12:30:01 +0000 chunk="5819d6f3d299ba0524777cb175e652                                                                                        9b" error_class=OpenSSL::SSL::SSLError error="SSL_write: unknown alert type"
  2019-02-11 12:29:04 +0000 [warn]: #0 suppressed same stacktrace
2019-02-11 12:30:01 +0000 [error]: #0 The other error occurs in out_mqtt.,OpenSSL::SSL::SSLError,SSL_write: unknown alert type
2019-02-11 12:30:01 +0000 [error]: #0 Retry in 1 sec

**Comment by toyokazu** [comment]
Hi,

Could you check #12? If you have some more information to debug, would you kindly provide it?

Best Regards
